name: Deploy to GitHub Pages

on:
    push:
        branches: [main] # Triggers when code is pushed to main branch
    workflow_run:
        workflows: ["Counter Handler", "Artifact Saver"] # Also trigger after counter updates
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PAT_TOKEN }}
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ vars.OWNER_NAME }}/${{ vars.REPO_NAME }}.git

            - name: Setup Project
              run: |
                  mkdir -p ${{ vars.PROJECT_DIR }}/counters

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: gh-pages
                  folder: .
                  token: ${{ secrets.PAT_TOKEN }}
                  commit-message: "Deploy to GitHub Pages"
                  clean: true
                  single-commit: true
