name: Increment Visit Counter

on:
  repository_dispatch:
    types: [increment-counter]
  # schedule:
    # - cron: '0 * * * *' # Run every hour
  workflow_dispatch:
    inputs:
      project_name:
        description: 'Name of the project'
        required: true
      new_count:
        description: 'New count for the project'
        required: false

env:
  PROJECT_FILES_DIR: project-files

jobs:
  increment-counter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure counters directory exists
        run: |
          mkdir -p project-files/counters

      - name: Increment or update counter
        run: |
          PROJECT_NAME=${{ github.event.client_payload.project_name }}
          NEW_COUNT=${{ github.event.client_payload.new_count }}
          COUNTER_FILE="project-files/counters/${PROJECT_NAME}.txt"
          if [ ! -f "$COUNTER_FILE" ]; then
            echo "0" > "$COUNTER_FILE"
          fi
          if [ -z "$NEW_COUNT" ]; then
            COUNT=$(cat "$COUNTER_FILE")
            COUNT=$((COUNT + 1))
          else
            COUNT=$NEW_COUNT
          fi
          echo $COUNT > "$COUNTER_FILE"

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add project-files/counters/${{ github.event.client_payload.project_name }}.txt
          git commit -m "Update counter for ${{ github.event.client_payload.project_name }}"
          git push
